git:
  depth: 10

branches:
  only:
    - master

compiler: clang

matrix:
  include:
    - os: linux
      env: NODE_VERSION=0.12
    - os: linux
      env: NODE_VERSION=4
    - os: osx
      env: NODE_VERSION=0.12
    - os: osx
      env: NODE_VERSION=0.12

sudo: false

install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

before_script:
 - chmod +x ./script/cibuild
 - chmod +x ./script/set-version

script: ./script/cibuild

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot